import { Agent, KanbanTask, Session, Message } from '@/types';

export const AGENTS: Agent[] = [
  {
    id: 'claude',
    name: 'Claude',
    color: '#ff9500',
    model: 'claude-3-5-sonnet',
    status: 'online',
    description: 'Anthropic\'s flagship model. Thoughtful, nuanced reasoning and long-context analysis.',
    stats: { likes: 2891, comments: 441, shares: 112 },
  },
  {
    id: 'openclaw',
    name: 'OpenClaw',
    color: '#00d4ff',
    model: 'gpt-4o',
    status: 'online',
    description: 'OpenAI-powered agent with multimodal capabilities and function calling.',
    stats: { likes: 1204, comments: 289, shares: 67 },
  },
  {
    id: 'hermes',
    name: 'Hermes',
    color: '#7c3aed',
    model: 'hermes-3-70b',
    status: 'online',
    description: 'Nous Research agent. Sessions, skills, kanban — and a chat line.',
    stats: { likes: 1397, comments: 301, shares: 55 },
  },
  {
    id: 'antigravity',
    name: 'Antigravity',
    color: '#00ff9d',
    model: 'mixtral-8x22b',
    status: 'idle',
    description: 'Multi-agent orchestration specialist with tool use and code generation.',
    stats: { likes: 876, comments: 154, shares: 33 },
  },
  {
    id: 'codex',
    name: 'Codex',
    color: '#ff5f57',
    model: 'deepseek-coder-v2',
    status: 'online',
    description: 'Code-first agent. Reviews, refactors, and ships production-grade software.',
    stats: { likes: 3102, comments: 567, shares: 201 },
  },
  {
    id: 'kimicode',
    name: 'Kimi Code',
    color: '#00b4ff',
    model: 'kimi-k1.5',
    status: 'idle',
    description: 'Moonshot AI\'s long-context reasoning model with 128k context window.',
    stats: { likes: 654, comments: 98, shares: 22 },
  },
  {
    id: 'glm52',
    name: 'GLM 5.2',
    color: '#ff3b71',
    model: 'glm-4-plus',
    status: 'offline',
    description: 'Zhipu AI\'s latest bilingual model with strong multilingual capabilities.',
    stats: { likes: 421, comments: 67, shares: 14 },
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  hermes: [
    {
      id: '1',
      role: 'agent',
      content: 'Hermes-Jarvis online. Neural link established. How can I assist you today?',
      timestamp: '19:10:18',
      agentName: 'Hermes-Jarvis',
    },
    {
      id: '2',
      role: 'user',
      content: 'Run a briefing on the current agent pipeline status.',
      timestamp: '19:11:02',
    },
    {
      id: '3',
      role: 'agent',
      content: 'Scanning pipeline... 4 agents active, 2 idle, 1 offline. Mission Control shows 3 tasks in-progress. Paperclip orchestration nominal. Recommend syncing Antigravity before next deployment window.',
      timestamp: '19:11:08',
      agentName: 'Hermes-Jarvis',
    },
  ],
};

export const KANBAN_TASKS: KanbanTask[] = [
  {
    id: 'k1',
    title: 'Refactor memory module',
    description: 'Extract long-term memory into a dedicated service layer',
    agent: 'Codex',
    priority: 'high',
    status: 'in-progress',
  },
  {
    id: 'k2',
    title: 'Integrate Hermes tool-call schema',
    description: 'Map Hermes function signatures to OpenAI tool spec',
    agent: 'Hermes',
    priority: 'high',
    status: 'in-progress',
  },
  {
    id: 'k3',
    title: 'Build session replay viewer',
    description: 'Timeline UI for replaying agent conversation sessions',
    agent: 'Claude',
    priority: 'medium',
    status: 'review',
  },
  {
    id: 'k4',
    title: 'Wake word detection',
    description: 'Implement local wake-word model for voice activation',
    agent: 'Antigravity',
    priority: 'medium',
    status: 'backlog',
  },
  {
    id: 'k5',
    title: 'Agent benchmark suite',
    description: 'Run MMLU / HumanEval across all registered agents',
    agent: 'OpenClaw',
    priority: 'low',
    status: 'backlog',
  },
  {
    id: 'k6',
    title: 'Kanban → pipeline sync',
    description: 'Auto-create pipeline tasks from kanban cards',
    agent: 'Hermes',
    priority: 'medium',
    status: 'done',
  },
  {
    id: 'k7',
    title: 'Multilingual support',
    description: 'Route CJK queries through GLM 5.2 automatically',
    agent: 'GLM 5.2',
    priority: 'low',
    status: 'done',
  },
];

export const SESSIONS: Session[] = [
  {
    id: 's1',
    name: 'Briefing — Pipeline Status',
    agent: 'Hermes',
    messages: 14,
    lastActive: '19:18',
    preview: 'Scanning pipeline... 4 agents active, 2 idle...',
  },
  {
    id: 's2',
    name: 'Code Review: memory.ts',
    agent: 'Codex',
    messages: 31,
    lastActive: '18:45',
    preview: 'The recursive call on line 88 will overflow for large...',
  },
  {
    id: 's3',
    name: 'Architecture Planning',
    agent: 'Claude',
    messages: 22,
    lastActive: '17:30',
    preview: 'I\'d recommend a microservices approach here, separating...',
  },
  {
    id: 's4',
    name: 'Data Pipeline Debug',
    agent: 'Antigravity',
    messages: 9,
    lastActive: '16:12',
    preview: 'The batch size of 512 is causing the OOM error. Try 128...',
  },
];
